### ISSUE TITLE
Lift the requirement to blit the swapchain image

### ISSUE THREAD

**Issue by kvark** [Ealrann/VSand#21]
It looks like the code issues a `vkCmdBlitImage` operation on a swapchain image without checking if the `TRANSFER_SRC`/`TRANSFER_DST` usages are even supported on the swapchains by calling `vkGetPhysicalDeviceSurfaceCapabilitiesKHR`.

Vulkan doesn't guarantee that anything but COLOR_ATTACHMENT usage is supported. Could we have VSand compatible with such drivers?

**Comment by Ealrann** [comment]
Ok, I'm working on an alternative pipeline:

#### Current pipeline

* *blit* **boardImage** into **swapImage**

I plan to keep this first pipeline as a default (when swapchain support it), since it's probably lighter.

#### Compatibility pipeline

1. *blit* **boardImage** into **colorAttachment** (with transfer usage)
2. *vkCmdDraw* with **colorAttachment** (as input attachment) into **swapImage**

Is that ok for your driver ?

**Comment by kvark** [comment]
Sure, that would be compatible. Thank you!

**Comment by Ealrann** [comment]
Ok, this commit should help. You can use something like `git pull --rebase --recurse-submodules` on the root directory to update the repo.

**Comment by kvark** [comment]
<img width="1244" alt="Screen Shot 2020-04-08 at 10 05 29" src="https://user-images.githubusercontent.com/107301/78793787-e2703280-7980-11ea-9868-389882de5f24.png">

**Comment by Ealrann** [comment]
Yeay ! Thank you for your issue, I'm glad to make VSand a bit more standard.

Looks like there is a little problem with the surface resize. Did you had any error ?

**Comment by kvark** [comment]
Just running it I'm not seeing any errors, no. Is there a specific test you want me to try? I'm not really familiar with how to use VSand :)

**Comment by Ealrann** [comment]
You can press 'f' for fullscreen.

**Comment by kvark** [comment]
Interesting... it's constantly blinking in fullscreen.
Could you clarify what you meant by "problem with the surface resize"? How is it supposed to look like?

**Comment by Ealrann** [comment]
> How is it supposed to look like?

The UI should stick to the border of the screen.

> Could you clarify what you meant by "problem with the surface resize"? 

My bad, I checked the code, the UI resize depends on the GLFW Window resize. So no problem related to a Surface resize. Probably a different behaviour of GLFW I don't handle properly.

About the blink: I never saw this bug. Maybe I missed one layout transition somewhere ?

**Comment by Ealrann** [comment]
Ok, The UI resize is based on the GLFW Window resize. So it shouldn't be related to the Surface.

**Comment by kvark** [comment]
A layout transition would be a no-op on Metal (at least on our current implementation). Not sure what's going on there. If it's specific to us, I'll just follow up with an investigation later at some point.
