### ISSUE TITLE
gradlew run BUILD FAILED

### ISSUE THREAD

**Issue by djidit** [Ealrann/VSand#22]
I followed your instructions and get BUILD FAILD:   

# How to produce the error
- First ... setup a JDK 14  
- clone the repo using:  
git clone --recursive --single-branch --branch root https://github.com/Ealrann/VSand.git
- launch the game:
#Go to the VSand project directory
cd VSand/VSand/
#Use gradle to run it
./gradlew run

- Now I got the BUILD FAILED in 25s. After reading your instructions further,
I generated an access token and edit files.
- After second **gradlew run** I got the following message (only in 3s, at first run I got same message in 25s):

# OUTPUT of gradlew run
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':org.sheepy.vsand:run'.
> Could not resolve all task dependencies for configuration ':org.sheepy.vsand:runtimeClasspath'.
   > Could not resolve emf.standalone:org.eclipse.emf.common:2.21.0.
     Required by:
         project :org.sheepy.vsand > project :Lily-vulkan:org.sheepy.lily.vulkan.api > project :Lily-vulkan:org.sheepy.lily.game.api > project :Lily-core:org.sheepy.lily.core.api
      > Could not resolve emf.standalone:org.eclipse.emf.common:2.21.0.
         > Could not get resource 'https://maven.pkg.github.com/ealrann/emf-standalone/emf/standalone/org.eclipse.emf.common/2.21.0/org.eclipse.emf.common-2.21.0.pom'.
            > Username must not be null!
   > Could not resolve emf.standalone:org.eclipse.emf.ecore:2.21.0.
     Required by:
         project :org.sheepy.vsand > project :Lily-vulkan:org.sheepy.lily.vulkan.api > project :Lily-vulkan:org.sheepy.lily.game.api > project :Lily-core:org.sheepy.lily.core.api
      > Could not resolve emf.standalone:org.eclipse.emf.ecore:2.21.0.
         > Could not get resource 'https://maven.pkg.github.com/ealrann/emf-standalone/emf/standalone/org.eclipse.emf.ecore/2.21.0/org.eclipse.emf.ecore-2.21.0.pom'.
            > Username must not be null!
   > Could not resolve emf.standalone:org.eclipse.emf.ecore.xmi:2.21.0.
     Required by:
         project :org.sheepy.vsand > project :Lily-vulkan:org.sheepy.lily.vulkan.api > project :Lily-vulkan:org.sheepy.lily.game.api > project :Lily-core:org.sheepy.lily.core.api
      > Could not resolve emf.standalone:org.eclipse.emf.ecore.xmi:2.21.0.
         > Could not get resource 'https://maven.pkg.github.com/ealrann/emf-standalone/emf/standalone/org.eclipse.emf.ecore.xmi/2.21.0/org.eclipse.emf.ecore.xmi-2.21.0.pom'.
            > Username must not be null!

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

# What went wrong?
Are there any further instructions

**Comment by Ealrann** [comment]
Hello, 
Yes, there is one more step : you need to generate a GitHub token, to access a dependency (GitHub package).


"
Generate a token with repo and read package here: https://github.com/settings/tokens.
Fill the file ~/.gradle/gradle.properties :
```
github.username=<your github usename>
github.token=<the generated token>
```
"

It's tedious that GitHub still doesn't allow to retrieve the public packages without a token. Someday, I'll put this dependency directly in maven repo.

Let me know if you need more help!

**Comment by Ealrann** [comment]
I close the issue. No need of PAT anymore since commit 6762f411e.
